- pom.xml
Bump the version of `tis-parent-client` to `5.1.4` to update transient
dependency `tis-security-jwt` to `5.1.4`, which allows usage with
Cognito/AWS API Gateway.
TIS21-2477, TIS21-2474
> chore(deps): bump tis-parent-client from 4.2.1 to 5.1.4

- pom.xml
Reverts Health-Education-England/TIS-SYNC#146
> Revert "chore(deps): bump shedlock-provider-jdbc-template from 2.5.0 to 4.31.0"

- pom.xml
Reverts Health-Education-England/TIS-SYNC#155
I think we need to move from Java 1.8 to Java 11 for this.
> Revert "chore(deps): bump checkstyle from 9.0.1 to 10.0"

- .aws/task-definition-template.json
The deployed task is incorrectly using the `tis-trainee-sync` role
instead of its own `tis-sync` role.
The new roles have been created but need to be used during deployment.
TIS21-2842
TIS21-2844
> chore: fix task role

- pom.xml
- src/main/java/uk/nhs/tis/sync/dto/ProgrammeMembershipDmsDto.java
- src/main/java/uk/nhs/tis/sync/mapper/CurriculumMembershipMapper.java
- src/main/java/uk/nhs/tis/sync/mapper/ProgrammeMembershipMapper.java
- src/main/java/uk/nhs/tis/sync/service/DmsRecordAssembler.java
- src/test/java/uk/nhs/tis/sync/service/DmsRecordAssemblerTest.java
There may be a more elegant way of doing this. 
Also: until the Programme Membership refactoring in TCS is complete, we are caught with some awkward naming weirdness between programme / curriculum memberships (e.g. ProgrammeMembership comes from CurriculumMembership table 😱 )
TIS21-3076: Handle Programme Memberships
> feat: add ProgrammeMembership DMS DTO mapper

- pom.xml
- src/main/java/uk/nhs/tis/sync/service/PersonElasticSearchService.java
'...in where clause is ambiguous' SQL errors caused by changes in tis-tcs programmeMembership.sql
NO-TICKET
> fix: PersonElasticSearch SQL for PM refactor

- pom.xml
- src/main/java/uk/nhs/tis/sync/service/KinesisService.java
- src/test/java/uk/nhs/tis/sync/service/KinesisServiceTest.java
Dates in objects sent to kinesis should be serialized as timestamps,
currently they are serialized as a JSON object which is not compatible
with the downstream expectations.
TIS21-2997
TIS21-2999
> fix: kinesis record date serialization

- src/main/java/uk/nhs/tis/sync/job/PersonRecordStatusJob.java
The `BASE_QUERY` doesn't use any fields in CurriculumMembership, and personId, programmeStartDate, programmeEndDate all should come from ProgrammeMembership.
TIS21-2392
> feat: refactor personRecordStatus to use programmeMemberhship

- src/main/java/uk/nhs/tis/sync/job/TrustAdminSyncJobTemplate.java
`EntityManager`s are replaced each chunk (we should revisit this). It was refactored earlier but was not explicitly closed before being reassigned.
TIS21-3311: PersonStatus not updated when current programme is deleted
> fix: close EntityManager before replacing

- .aws/task-definition-template.json
TIS21-3229
In application.yml, the config for rabbitmq doesn't have the prefix, so remove them. 
https://github.com/Health-Education-England/TIS-SYNC/blob/bdf89db2595f3a126550f33d17992f6ba3e67450/src/main/resources/config/application.yml#L126
> fix:internal parameter names for rabbitmq

- pom.xml
- src/main/java/uk/nhs/tis/sync/api/JobResource.java
- src/main/java/uk/nhs/tis/sync/config/RabbitConfig.java
- src/main/java/uk/nhs/tis/sync/event/listener/JobRunningListener.java
- src/main/java/uk/nhs/tis/sync/job/reval/RevalCurrentPmSyncJob.java
- src/main/java/uk/nhs/tis/sync/message/publisher/RabbitMqTcsPmUpdatePublisher.java
- src/main/resources/config/application-local.yml
- src/main/resources/config/application.yml
- src/main/resources/static/index.html
- src/main/resources/static/main.js
- src/main/resources/static/style.css
- src/test/java/uk/nhs/tis/sync/api/JobResourceTest.java
- src/test/java/uk/nhs/tis/sync/event/listener/JobRunningListenerTest.java
Use `@Profile("!nimdta")` instead of "@ConditionXXX" to make everywhere consistent. I believe this would be easier for us to locate them in the future. But it requires the profile to contain `nimdta` first. 
depends on [TIS-OPS#507](https://github.com/Health-Education-England/TIS-OPS/pull/507)
TIS21-3229
> fix:remove RevalCurrentPmSyncJob from nimdta

- pom.xml
- src/main/java/uk/nhs/tis/sync/dto/CurriculumMembershipDmsDto.java
- src/main/java/uk/nhs/tis/sync/dto/CurriculumMembershipWrapperDto.java
- src/main/java/uk/nhs/tis/sync/dto/DmsDtoType.java
- src/main/java/uk/nhs/tis/sync/dto/ProgrammeMembershipDmsDto.java
- src/main/java/uk/nhs/tis/sync/mapper/CurriculumMembershipMapper.java
- src/main/java/uk/nhs/tis/sync/mapper/ProgrammeMembershipMapper.java
- src/main/java/uk/nhs/tis/sync/service/DataRequestService.java
- src/test/java/uk/nhs/tis/sync/service/DataRequestServiceTest.java
- src/test/java/uk/nhs/tis/sync/service/DmsRecordAssemblerTest.java
TSS needs the ability to request CurriculumMemberships and ProgrammeMemberships based on the associated Programme Membership UUID.
Currently the CurriculumMembershipDmsDto is made up of both CM and PM data, modify it to only contain CM data and move the PM data in to a new ProgrammeMembershipDmsDto.
Update the DataRequestService to handle requests for both CMs and PMs. A wrapper is needed for the CurriculumMembership so the PM UUID can be included, as the TCS CurriculumMembershipDTO does not include it.
TIS21-4173
TIS21-2399
> feat: handle PM and CM data requests

- src/main/java/uk/nhs/tis/sync/service/impl/PersonViewRowMapper.java
Before (now on Prod):
We can notice there're a lot of `0` in gradeId or siteId, because ResultSet.getLong() returns a 0 when the value is NULL, see documentation here: https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html
But we in the Decorator, we treat the data as NULL rather than 0: 
https://github.com/Health-Education-England/TIS-SYNC/blob/b76cfe545b0520ae89b917ddddd34e3da44a37c4/src/main/java/uk/nhs/tis/sync/service/api/decorator/PersonViewDecorator.java#L39
After (tested locally):
This will also benefit the `PersonViewDecorator` in TCS, as PersonViewDecorator decorates person views from ES with sites and grades from reference service.
TIS21-4739
> fix:set null values when last ResultSet col was null

- pom.xml
- src/main/java/uk/nhs/tis/sync/service/KinesisService.java
- src/test/java/uk/nhs/tis/sync/service/KinesisServiceTest.java
At the moment, tis-sync sends everything with partition key '0', e.g. PlacementSpecialty records coming in on shard 1 with partition key '0'. This should be adjusted to match the default schema.table partition keys (which put PlacementSpecialties onto shard 0, as a matter of fact).
TIS21-6028
TIS21-6030
> fix: use correct partition key for kinesis data

- .github/workflows/ci-cd-workflow.yml
While the project builds with Java 17, it has not been tested.
TIS21-6028: Sync to Self-Service in order
> chore: use JDK 17 for sonar

- .aws/task-definition-template.json
- pom.xml
Switched to using the parameter store entry that TSS uses as well.
Roll-out plan for this is itemised here: https://hee-tis.atlassian.net/browse/TIS21-6028?focusedCommentId=88927
TIS21-6136
> Fix: use new tss fifo queue

- pom.xml
- src/main/java/uk/nhs/tis/sync/dto/DmsDtoType.java
- src/main/java/uk/nhs/tis/sync/dto/LocalOfficeDmsDto.java
- src/main/java/uk/nhs/tis/sync/mapper/LocalOfficeMapper.java
- src/main/java/uk/nhs/tis/sync/service/DataRequestService.java
- src/test/java/uk/nhs/tis/sync/mapper/LocalOfficeMapperTest.java
- src/test/java/uk/nhs/tis/sync/service/DataRequestServiceTest.java
Dependent on https://github.com/Health-Education-England/TIS-REFERENCE/pull/343. Allow local office and DBC requests by abbreviation.
TIS21-6279
> feat: local office/DBC TSS requests 

- pom.xml
The PersonOwner job failed due to missing enum values. A GoldGuideVersion 10 was added but not everywhere.
chore: bump TCS Client
This also uses the API and is done for consistently choosing the latest available patches.
NO-CARD: Just Fixing It
> chore: bump TCS Persistence 2.32.0 -> 2.32.4

- .aws/task-definition-template.json
- pom.xml
- src/main/java/uk/nhs/tis/sync/dto/MetadataDto.java
- src/main/java/uk/nhs/tis/sync/job/RecordResendingJob.java
- src/main/java/uk/nhs/tis/sync/message/listener/RabbitMqTssRejectedGmcUpdateListener.java
- src/main/java/uk/nhs/tis/sync/model/GmcDetailsProvidedEvent.java
- src/main/java/uk/nhs/tis/sync/service/DataRequestService.java
- src/main/java/uk/nhs/tis/sync/service/DmsRecordAssembler.java
- src/main/resources/config/application.yml
- src/test/java/uk/nhs/tis/sync/job/RecordResendingJobTest.java
- src/test/java/uk/nhs/tis/sync/message/listener/RabbitMqTssRejectedGmcUpdateListenerTest.java
- src/test/java/uk/nhs/tis/sync/service/DataRequestServiceTest.java
- src/test/java/uk/nhs/tis/sync/service/DmsRecordAssemblerTest.java
- src/test/resources/config/application.yml
Include additional metadata in requested data to allow TSS to recognise data that is being resynced in response to rejected trainee-instigated updates (allowing for trainee notifications etc.).
Handle GMC Details data.
Listen to rabbit 'rejected update' queue for GMC details.
Related: 
https://github.com/Health-Education-England/TIS-RabbitMQ/pull/92 
https://github.com/Health-Education-England/TIS-OPS/pull/899
TIS21-6639
> Feat: listen to rejected rabbit msgs, include TIS metadata in data request msgs

- pom.xml
- src/main/java/uk/nhs/tis/sync/message/listener/RabbitMqTssRejectedGmcUpdateListener.java
- src/test/java/uk/nhs/tis/sync/message/listener/RabbitMqTssRejectedGmcUpdateListenerTest.java
Omitted due to forgetting that local env queues differ from 'real' queues in this respect 🤦 
TIS21-6639
> fix: set msg attribs for sending to FIFO SQS
